name: Run Python Script On Test Files

on:
  push:
  pull_request:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: unviz_env.yml
          environment-name: unviz
          cache-environment: true
          init-shell: bash


      - name: Verify environment
        shell: bash -l {0}
        run: |
          micromamba info
          which python
          python --version
          micromamba list


      - name: Run script on all test files
        shell: bash -l {0}
        run: |
          for file in tests/*; do
            echo "Running on $file"
            python src/mcstas_to_cad.py --input_file="$file"
            python src/union_viewer --input_file="$file"
          done
