name: Run Python Script On Test Files

on:
  push:
  pull_request:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.14"
          activate-environment: unviz
          environment-file: unviz_env.yml

      - name: Verify conda
        shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: Run script on all test files
        run: |
          for file in tests/*; do
            echo "Running on $file"
            python3 src/mcstas_to_cad.py --input_file="$file"
          done
